# OBJECTIVE: obtain pseudo multi-view images for concept prior learning

obj_name=$1
PROMPT=$2
round_1_rendering_path=$3
NORMAL='' # unuse, normals generated by Wonder3D
max_train_steps=150

INSTANCE_DIR="./data/data_rgb"$NORMAL"/"$obj_name""
OUTPUT_DIR="./ckpt/base_model/"$obj_name"_text"

MODEL_NAME="stabilityai/stable-diffusion-2-1-base"
accelerate launch --config_file ../configs/acc_config.yaml --main_process_port $6 --num_processes 1 --gpu_ids "$5" train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="$PROMPT" \
  --resolution=512 \
  --train_batch_size=8 \
  --gradient_accumulation_steps=1 \
  --learning_rate="$7" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps="$max_train_steps" \
  --train_text_encoder \
  --checkpointing_steps="$max_train_steps" \
  --seed=$8 \

CUDA_VISIBLE_DEVICES="$5" python img2img.py \
    --round_1_rendering_path=$round_1_rendering_path \
    --obj_name=$obj_name \
    --prompt="$PROMPT" \
    --normal="$NORMAL" \